[package]
name = "clap-plugin"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap-sys = { git = "https://github.com/glowcoil/clap-sys" }
clap-audio-core = { path = "core" }

[workspace]
members = ["core", "examples/gain", "host", "params"]