[package]
name = "clap-audio-host"
version = "0.1.0"
edition = "2021"

[dependencies]
clap-sys = { git = "https://github.com/prokopyl/clap-sys" }
clap-audio-plugin = { path = "../plugin" } # TODO: remove
clap-audio-common = { path = "../common" }
basedrop = "0.1.2"
libloading = "0.7.2"
