[package]
name = "clack-extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clack-plugin = { path = "../plugin", optional = true }
clack-host = { path = "../host", optional = true }
clack-common = { path = "../common" }
clap-sys = { git = "https://github.com/prokopyl/clap-sys", branch = "clap-0-18" }
bitflags = "1.3.2"

[features]
audio-ports = []
latency = []
log = []
params = []
state = []
