[package]
name = "clack-extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clack-plugin = { path = "../plugin" }
clack-host = { path = "../host" }
clack-common = { path = "../common" }
clap-sys = { git = "https://github.com/prokopyl/clap-sys" }
bitflags = "1.3.2"
