[package]
name = "clack-extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clack-plugin = { path = "../plugin", optional = true }
clack-host = { path = "../host", optional = true }
clack-common = { path = "../common" }
clap-sys = "0.3.0"
raw-window-handle = { version = "0.4.2", optional = true }
bitflags = "1.3.2"

[features]
audio-ports = []
event-registry = []
latency = []
log = []
note-ports = []
params = []
state = []
gui = []
gui-attached = ["gui", "raw-window-handle"]
thread-check = []
