[package]
name = "clack-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap-sys = { git = "https://github.com/prokopyl/clap-sys", branch = "clap-0-18" }
bitflags = "1.3.2"
